#!/usr/bin/env bash

ROOT_DIR=`realpath "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."`

ROOT=$(realpath ${ROOT_DIR}/../..)
PROJECT=$(basename ${ROOT_DIR} .git)

${ROOT}/bin/console update ${PROJECT}
