# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.form_login_authenticator:
        class: AppBundle\Security\FormLoginAuthenticator

    app.sha_finder:
        class: AppBundle\Service\ShaFinder
        arguments:
            - '%kernel.project_dir%'

    app.ssh_handler:
        class: AppBundle\Service\SshHandler
        arguments:
            - '%git_user%'
        public: true

    app.project_handler:
        class: AppBundle\Service\ProjectHandler
        arguments: ['%kernel.project_dir%', '%git_user%']
        public: true

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
