# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.form_login_authenticator:
        class: AppBundle\Security\FormLoginAuthenticator
        arguments: ["@router", "@security.password_encoder"]

    app.sha_finder:
        class: AppBundle\Service\ShaFinder
        arguments:
            - '%kernel.root_dir%'

    app.ssh_handler:
        class: AppBundle\Service\SshHandler
        arguments:
            - '%git_user%'

    app.project_handler:
        class: AppBundle\Service\ProjectHandler
        arguments:
            - '%kernel.root_dir%'
            - '%repo_dir%'
            - '%work_dir%'
            - '%web_dir%'
            - '%git_user%'
            - '%sys_dirs%'

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        arguments:
            - '@app.sha_finder'
        tags:
            - { name: twig.extension }
